const result = {
  organisationId: 92,
  name: "O7",
  displayName: "O7",
  description: null,
  tenantId: 53,
  parentOrganisationId: null,
  organisationMember: [
    {
      organisationMemberId: 85,
      organisationId: 92,
      userDetailsId: 1892,
      isOwner: false,
      organisation: {
        organisationId: 92,
        name: "O7",
        displayName: "O7",
        description: null,
        tenantId: 53,
        parentOrganisationId: null,
        organisationMember: null,
        childOrg: null,
      },
      userDetails: {
        userDetailsId: 1892,
        userName: "T4@tcs.com",
        givenName: null,
        surname: null,
        displayName: null,
        mail: null,
        mobilePhone: null,
        businessPhones: null,
        officeLocation: null,
        jobTitle: null,
        locked: null,
        passwordExpired: null,
        imageType: null,
        preferences: null,
        tenantId: null,
        photo: null,
      },
    },
    {
      organisationMemberId: 92,
      organisationId: 92,
      userDetailsId: 67,
      isOwner: true,
      organisation: {
        organisationId: 92,
        name: "O7",
        displayName: "O7",
        description: null,
        tenantId: 53,
        parentOrganisationId: null,
        organisationMember: null,
        childOrg: null,
      },
      userDetails: {
        userDetailsId: 67,
        userName: "T2@tcs.com",
        givenName: "T2@tcs.com",
        surname: "Test",
        displayName: null,
        mail: null,
        mobilePhone: null,
        businessPhones: null,
        officeLocation: null,
        jobTitle: null,
        locked: null,
        passwordExpired: null,
        imageType: null,
        preferences: null,
        tenantId: null,
        photo: null,
      },
    },
  ],
  childOrg: [
    {
      organisationId: 93,
      name: "O1",
      displayName: "O1",
      description: null,
      tenantId: 53,
      parentOrganisationId: 92,
      organisationMember: [
        {
          organisationMemberId: 86,
          organisationId: 93,
          userDetailsId: 68,
          isOwner: true,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 68,
            userName: "T3@tcs.com",
            givenName: "T3@tcs.com",
            surname: "Test",
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
        {
          organisationMemberId: 87,
          organisationId: 93,
          userDetailsId: 1892,
          isOwner: false,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 1892,
            userName: "T4@tcs.com",
            givenName: null,
            surname: null,
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
        {
          organisationMemberId: 93,
          organisationId: 93,
          userDetailsId: 66,
          isOwner: false,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 66,
            userName: "T1@tcs.com",
            givenName: "T1Owner",
            surname: "Test",
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
        {
          organisationMemberId: 94,
          organisationId: 93,
          userDetailsId: 67,
          isOwner: false,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 67,
            userName: "T2@tcs.com",
            givenName: "T2@tcs.com",
            surname: "Test",
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
        {
          organisationMemberId: 95,
          organisationId: 93,
          userDetailsId: 1893,
          isOwner: false,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 1893,
            userName: "T5@tcs.com",
            givenName: null,
            surname: null,
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
        {
          organisationMemberId: 96,
          organisationId: 93,
          userDetailsId: 1920,
          isOwner: false,
          organisation: {
            organisationId: 93,
            name: "O1",
            displayName: "O1",
            description: null,
            tenantId: 53,
            parentOrganisationId: 92,
            organisationMember: null,
            childOrg: null,
          },
          userDetails: {
            userDetailsId: 1920,
            userName: "T6@tcs.com",
            givenName: null,
            surname: null,
            displayName: null,
            mail: null,
            mobilePhone: null,
            businessPhones: null,
            officeLocation: null,
            jobTitle: null,
            locked: null,
            passwordExpired: null,
            imageType: null,
            preferences: null,
            tenantId: null,
            photo: null,
          },
        },
      ],
      childOrg: [
        {
          organisationId: 96,
          name: "O6",
          displayName: "O6",
          description: null,
          tenantId: 53,
          parentOrganisationId: 93,
          organisationMember: [
            {
              organisationMemberId: 97,
              organisationId: 96,
              userDetailsId: 68,
              isOwner: true,
              organisation: {
                organisationId: 96,
                name: "O6",
                displayName: "O6",
                description: null,
                tenantId: 53,
                parentOrganisationId: 93,
                organisationMember: null,
                childOrg: null,
              },
              userDetails: {
                userDetailsId: 68,
                userName: "T3@tcs.com",
                givenName: "T3@tcs.com",
                surname: "Test",
                displayName: null,
                mail: null,
                mobilePhone: null,
                businessPhones: null,
                officeLocation: null,
                jobTitle: null,
                locked: null,
                passwordExpired: null,
                imageType: null,
                preferences: null,
                tenantId: null,
                photo: null,
              },
            },
            {
              organisationMemberId: 98,
              organisationId: 96,
              userDetailsId: 1892,
              isOwner: false,
              organisation: {
                organisationId: 96,
                name: "O6",
                displayName: "O6",
                description: null,
                tenantId: 53,
                parentOrganisationId: 93,
                organisationMember: null,
                childOrg: null,
              },
              userDetails: {
                userDetailsId: 1892,
                userName: "T4@tcs.com",
                givenName: null,
                surname: null,
                displayName: null,
                mail: null,
                mobilePhone: null,
                businessPhones: null,
                officeLocation: null,
                jobTitle: null,
                locked: null,
                passwordExpired: null,
                imageType: null,
                preferences: null,
                tenantId: null,
                photo: null,
              },
            },
          ],
          childOrg: null,
        },
      ],
    },
  ],
};

const final = [];
function getResult(data, manager) {
  if (data?.organisationMember?.length > 0) {
    const om = data?.organisationMember;
    const ownerDetails = om?.filter((values) => values.isOwner);

    for (let i = 0; i < om?.length; i++) {
      const orgItemData = {
        Id: '' + om[i]?.userDetails?.userDetailsId + ''+ om[i]?.organisation?.organisationId,
        displayName: om[i]?.organisation?.displayName,
        userName: om[i]?.userDetails?.userName,
        Manager: om[i]?.isOwner
          ? manager
          : '' + ownerDetails[0]?.userDetails?.userDetailsId + ''+ ownerDetails[0]?.organisation?.organisationId,
      };

      final.push(orgItemData);
    }

    if (data?.childOrg?.length) {
      for (let i = 0; i < data?.childOrg?.length; i++) {
        getResult(
          data?.childOrg[i],
          '' + ownerDetails[i]?.userDetails?.userDetailsId + ''+ ownerDetails[i]?.organisation?.organisationId
        );
      }
    } return final;
  }
}

console.log(getResult(result, ''));
